### ISSUE TITLE
waste: waste is not updating the stock chart

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/move#109]

**Comment by janetbutts** [comment]
@futuresandwich & @mfcm , i thought this was a defect, but the team remembers that this may have been left out intentionally. can you please comment? should waste count impact the chart?

**Comment by mfcm** [comment]
Yes, waste should be reflected in the chart.

MFCM

2015-06-29 15:11 GMT+01:00 janetbutts <notifications@github.com>:
