### ISSUE TITLE
stock-out alert is not reaching the dashboard

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/move#122]
on or off line stock counts are not reaching the dashboard. please check couchdb

**Comment by freefony** [comment]
Seem to be working, i just sent one from Test Facility and it's on the
dashboard. I also see some, you probably sent earlier, on there too.

**Comment by freefony** [comment]
Ok. so i tested for offline stock-out alert, and it's not reaching the
server although the app is sending out sms, i tell from my credit
deductions 😊,  so it has to be dispatch or telerivet

**Comment by janetbutts** [comment]
@freefony, this looks resvoled. Can you confirm and close if so?
