### ISSUE TITLE
waste count screen on dashboard displays "error loading data"

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/move#123]
![screen shot 2015-07-02 at 9 36 04 pm](https://cloud.githubusercontent.com/assets/8954337/8487188/22ff6672-2102-11e5-99b3-f6bca1c8cfdb.png)

**Comment by musamusa** [comment]
@janetbutts this has been fixed last time I checked, it was related to a missing database (discard_count was missing on production)

**Comment by janetbutts** [comment]
thanks @musamusa , will close the ticket
