### ISSUE TITLE
Using Deprecated Cordova SMS plugin

### ISSUE THREAD

**Issue by jofomah** [eHealthAfrica/move#138]

**Comment by jofomah** [comment]
Currently we are using this plugin for sending SMS:cca plugin add https://github.com/aharris88/phonegap-sms-plugin.git

this has been deprecated, we should upgrade to https://github.com/cordova-sms/cordova-sms-plugin

**Comment by tlvince** [comment]
@jofomah could you give e05015ca43d773abac66f84a19ee18890938e964 a test when you can?
