### ISSUE TITLE
create a reporting database for move

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/move#161]
there has been a request to create a landing page that pulls from many of the move databases. it would be helpful if there was a database that consolidates these data.

**Comment by tlvince** [comment]
@janetbutts can we run through this? What's the goal of the landing page? Charting? Which databases are pertinent?

**Comment by tlvince** [comment]
@jofomah do you know any specifics on the requirements for this?

**Comment by janetbutts** [comment]
no longer valid. closing
