### ISSUE TITLE
build move staging server

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/move#165]
please build an AWS instance that has something like `stage.lomis.ehealth.org.ng` and a db that has url such as `stage.lomis.ehealth.org.ng:5984` 

then we need to set up the dashboard on stage.lomis.ehealth.org.ng and replicate production dbs to `stage.lomis.ehealth.org.ng` so that we have production data on stage. 

so it should be basically same as dev or production just that it will point to `stage.lomis.ehealth.org.ng` and db points to `http://stage.lomis.ehealth.org:5984'

then the db user login details

**Comment by nycdubliner** [comment]
@janetbutts 
I've brought up a new server for this, but I found an existing host.

Is there an issue with lomis-stage.ehealth.org.ng?
(It's up and running, but doesn't currently have couchdb, which I'd be happy to install.)
T.

notes from server build:
ANSIBLE_HOST_KEY_CHECKING=False \
ansible-playbook -vvvv  \
-e "ansible_ssh_user=ubuntu" -e "country=gn"  \
-e "CreatedBy=Tiarnan" --private-key=~/.ssh/aws-deploy.pem  \
-e "RequestedBy=Janet" \
projects/server-setup/lomis-server-setup.yml

IP: 52.18.200.164

**Comment by nycdubliner** [comment]
lomis-stage is up and ready for use. 
lomis-stage.ehealth.org.ng:5984/_utils/

Password in the spreadsheet. (Lomis worksheet.)

@tlvince  you can login with ubuntu@lomis-stage.ehealth.org.ng.
@janetbutts I couldn't find your keys on github. Can you upload them and I'll add them to the server?

(Usually they'd appear something like: https://github.com/tlvince.keys)

**Comment by tlvince** [comment]
Works for me :) Shall we replicate prod over?

**Comment by janetbutts** [comment]
@tlvince , do you know where the keys are?

**Comment by tlvince** [comment]
@nycdubliner is talking about SSH keys. I don't think you need (or want) shell access to the server?

**Comment by nycdubliner** [comment]
That is what I'm talking about. :)
@tlvince Do you need anything else from me or can I close the ticket?
Thanks.
T.

**Comment by tlvince** [comment]
S'all good. Cheers.

**Comment by janetbutts** [comment]
@nycdubliner , i just went to lomis-stage.ehealth.org.ng to take a look. i'm getting a "502 bad gateway" error. @tlvince , is this built and we are just waiting on configuration? if so, i'll hold tight and you can let me know when to check again.

**Comment by tlvince** [comment]
Its configuration; it doesn't have access to Couch. Working on it.

**Comment by tlvince** [comment]
@janetbutts working now
