### ISSUE TITLE
correct emails on facilities.

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/move#166]
Replace the emails that begin with "hf." with the ones that begin with "}wto." on the facility record:

wto.zuga_hp.takai@kano.org.ng	hf.zuga.takai@kano.org.ng

wto.inusawa_hp.ungogo@kano.org.ng	hf.inusawa.ungogo@kano.org.ng

wto.sabo_garba_phc.fagge@kano.org.ng	hf.sabo_garba.dala@kano.org.ng

wto.kanawa_hp.sumaila@kano.org.ng	hf.kanawa.sumaila@kano.org.ng

**Comment by janetbutts** [comment]
hey @musamusa , i just saw that i didn't assign this. please double check as you may have already done this.

**Comment by musamusa** [comment]
I already passed it on to @norbert to implement, still waiting for any response from him.

**Comment by tlvince** [comment]
See https://github.com/eHealthAfrica/move-migrate-facility-emails

**Comment by tlvince** [comment]
Emails have been corrected on staging. Please confirm, then I'll update production.

**Comment by tlvince** [comment]
Handing over for confirmation. Please reassign back to me if stage looks ok.

**Comment by yusufscratch** [comment]
@tlvince Successfully tested the new user accounts.

**Comment by tlvince** [comment]
@yusufscratch thanks. I'll update production then.

**Comment by tlvince** [comment]
Production updated.
