### ISSUE TITLE
push facility database from dev to staging then after that, to production

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/move#202]
@musamusa has updated the facility database. we need to have those changes pushed to staging, then to production once QAed

**Comment by musamusa** [comment]
@janetbutts this is a link to the file 
https://dl-web.dropbox.com/get/mym/updated.json?_subject_uid=36151695&w=AABaBaHmHpATjmjClUBgdTYg4_mlHX-E-eTaS_9Y13SbzQ

**Comment by janetbutts** [comment]
hi @norbert, can this get done today?

**Comment by musamusa** [comment]
@norbert this is the update for app_config as promised
https://www.dropbox.com/s/285qto9javpeb6t/updated-app-config.json?dl=0

**Comment by tlvince** [comment]
Can this be closed?

**Comment by norbert** [comment]
Yes.
