### ISSUE TITLE
Specify what is slow in the dashboard

### ISSUE THREAD

**Issue by karlwestin** [eHealthAfrica/move#33]
@jofomah i need your help here:
I need you to give me a list of the things that should become faster in the refactored LoMIS.
If we dont know what we're measuring we cant measure it

It should be stuff like 'searching by location in field X in this dashboard'. The best would be to describe user actions, not lines of code. 

Thanks

**Comment by karlwestin** [comment]
One example i could add myself:

When first opening the app, the spinner is spinning for very long time (waiting for the 'unopened' request)
![screen shot 2015-06-08 at 13 45 13](https://cloud.githubusercontent.com/assets/359947/8034068/a3267b28-0de4-11e5-9fe9-6df8aaf4986e.png)

**Comment by jofomah** [comment]
- Documents are built from multiple requests, for instance to show a stock count, separate request is used to pull Facility and Product Types information

- Filtering is slow

- To load stock count page data before processing requires three requests (https://github.com/eHealthAfrica/LMIS-Dashboard/blob/develop/client/components/api/stock_count_factory.js#L53 and then this https://github.com/eHealthAfrica/LMIS-Dashboard/blob/develop/client/components/api/stock_count_factory.js#L147)

Most of it boils down to `document type per DB` model, will it help if we set up a call 
whenever is convenient for you to discuss this?

**Comment by karlwestin** [comment]
thanks a lot, this is really helpful!

**Comment by tlvince** [comment]
Move into relevant issues in https://github.com/eHealthAfrica/LMIS-Dashboard
