### ISSUE TITLE
move DD couchdb to a separate instance

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/move#43]
DD and LoMIS need to be on separate instances since dev will disable admin party on LoMIS. We need to enable DD dashboard to production ASAP. Also, see https://github.com/eHealthAfrica/direct-delivery-dashboard/issues/7 .

**Comment by jofomah** [comment]
We will need the following:
 
1. A separate CouchDB server instance for Direct Delivery.
2. An AWS Server setup for running Direct Delivery CouchDB server, Direct Delivery Importer and Direct Delivery Dashboard
3. Currently, Direct Delivery dev dashboard is deployed on CloudFoundry, ping @tlvince if you need more detail about that.

**Comment by nycdubliner** [comment]
Hi, 

Can you give a little more detail. We shouldn't be using admin party on internet facing systems. 

I don't mind moving to two parallel stacks running on separate servers, but the servers shouldn't be open to the world.
Thanks.
T.

**Comment by nycdubliner** [comment]
(closed by accident.)

**Comment by jofomah** [comment]
@nycdubliner 
Direct Delivery CouchDB database is currently one of the databases on Ebola CouchDB server, we have user account management feature on Direct Delivery Dashboard that requires Admin Access so we (can't remember exactly who, Tom, Justin ... i think) that we are better off creating a fresh CouchDB server for Direct Delivery so we won't have to share admin credentials across projects.

LoMIS CouchDB database is currently open and we are currently working to fix that.

**Comment by nycdubliner** [comment]
For direct delivery: This is a dev server and you just need couchdb installed on linux?

Re LoMIS: When is this getting fixed and where is it being tracked?

**Comment by janetbutts** [comment]
@nycdubliner, we asked for a production instance for the DD dashboard a while back.  So we need to retain our dev instance and have a prod instance. https://github.com/eHealthAfrica/direct-delivery-dashboard/issues/7

Re LoMIS(Move): We are in the process disabling admin party and updating the application right now. https://github.com/eHealthAfrica/LMIS-Chrome/issues/577 . We are testing it first in dev environment. It's turned out to be a bigger task than initially thought.

**Comment by jofomah** [comment]
@nycdubliner 

Direct Delivery has three parts, Direct Delivery mobile app, Dashboard and Direct Delivery importer.

Currently, Direct Delivery Importer which is a daemon script is deployed on LoMIS server and uses `dev.couchdb.ebola.eocng.org` CouchDB server, the dashboard which is still in dev is deployed on CloudFoundry. we are thinking of

- A separate server for Direct Delivery Dashboard, Importer and CouchDB server.

**Comment by norbert** [comment]
There are separate CouchDB instances for different environments now.
