### ISSUE TITLE
Extract build scripts

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#46]
With the aim to bring the apps closer together, it'd be nice to extract the build scripts into their own thing.

Currently, we have at least three variations:

* [LoMIS](https://github.com/eHealthAfrica/LMIS-Chrome/tree/3bcb53c1882757a4645139f1a2cbeb4ba9d5b64d/scripts)
* [Sense-followup](https://github.com/eHealthAfrica/lr-sense-ebola-followup/tree/55f719ba393a82b8851caea6b58c78978fbe9db2/scripts)
* [NutSurv](https://github.com/eHealthAfrica/NutSurv-Mobile/tree/5ed65bb041c4fe96fc585c11a912cbd1cfde3d71/scripts)

First step would be to find out the differences between them.

**Comment by jo** [comment]
During this step it might be worth looking into [couchdb-bootstrap](https://github.com/eHealthAfrica/couchdb-bootstrap), which can push couchdb documents / views, configure the server and do everything you need related to CouchDB setup.
The project is ready and I plan to use it for the mnutrition today.

**Comment by rmehner** [comment]
@tlvince happy to assist on the Android build side of things.

**Comment by karlwestin** [comment]
@jo this is more about the cordova build than any couchdb work, i'd rather not mix those 2 up

**Comment by jo** [comment]
OK sorry, just read build script and saw a [push_views.sh](https://github.com/eHealthAfrica/lr-sense-ebola-followup/blob/55f719ba393a82b8851caea6b58c78978fbe9db2/scripts/push_views.sh) ;)

**Comment by tlvince** [comment]
Closed via #64.
