### ISSUE TITLE
memory store is empty

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#51]
After completing app config (and waiting in the home screen), hitting refresh shows:

![screen shot 2015-06-10 at 15 40 13](https://cloud.githubusercontent.com/assets/323761/8085944/cb00fd60-0f8a-11e5-8db2-462f4132993a.png)

**Comment by jofomah** [comment]
we just had this error after changes on LoMIS, https://github.com/jofomah/LMIS-Chrome/commit/2767b079602139a850b80d8c790291d2a37d2c94 is just a fix, but the main problem is we need to check if app config exists on app start up and if so, load local data into memory store. Unless you want to deprecate memory store.

**Comment by karlwestin** [comment]
I got as far as this:
when you re-load, the app is already on the main-activity route. If i remove the 'main-activity' from the url and reload, i don't see the error. So what needs to happen might be that the main-activity route need to wait for fixtureLoadingService to load the dbs in memory before resolving. That could be a cached promise.. Let's have a quick chat tomorrow!
