### ISSUE TITLE
Cannot use the app without logging in at least once

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#67]
If I'm offline (or otherwise can't reach CouchDB) and this is a fresh install, I'm shown:

![screen shot 2015-06-17 at 17 21 50](https://cloud.githubusercontent.com/assets/323761/8212790/ac9c5da2-1515-11e5-94d0-7784df44f0c1.png)

> You can cancel and continue using the app offline, too.

… suggests I can still use the app, when I can't; the user needs to have logged in at least once to be able to work offline.

**Comment by janetbutts** [comment]
@freefony, please change the error message and omit the list "you can cancel and continue using the app offline, too."

**Comment by freefony** [comment]
closed by #112
